local L = LibStub("AceLocale-3.0"):NewLocale("SinestraWrackHelper", "enUS", true, true)

L["The color of the status bar when the bar has reached its max (when wrack should be dispelled)"] = true
L["Scale"] = true
L["Right"] = true
L["Bar Height"] = true
L["Check to show this font string, uncheck to hide"] = true
L["Whether the bars should expand upwards or downwards."] = true
L["Thin Outline"] = true
L["Maximum Bar value"] = true
L["Bar Spacing"] = true
L["Font color"] = true
L["Font - Time Active"] = true
L["Side of bar to anchor to"] = true
L["Bar Width"] = true
L["Check to show this lock the movement and hide test bars, uncheck to unlock movement and show test bars"] = true
L["Configue the icon that is displayed to the side of the bar showing various buffs on the bar's unit that affect wrack"] = true
L["Down"] = true
L["Font Face"] = true
L["Font Size"] = true
L["Font outline style"] = true
L["Font - Player Name"] = true
L["X offset"] = true
L["Y offset"] = true
L["Locked"] = true
L["Options"] = true
L["Icon Options"] = true
L["Left"] = true
L["The amount of space between each bar"] = true
L["Font - Last Damage"] = true
L["Click and drag bars to reposition. '/swh options' to display the options. '/swh' to leave config mode."] = true
L["Up"] = true
L["End color"] = true
L["The color of the status bar when wrack has just been applied to a player"] = true
L["Start color"] = true
L["Bar Options"] = true
L["Colors"] = true
L["Growth Direction"] = true
L["No Outline"] = true
L["Enabled"] = true
L["Thick Outline"] = true
L["Check to show the icons to the side of bars that show various buffs that affect wrack's damage, uncheck to hide"] = true
L["The time, in seconds, that the bar will be full at. Higher times than this value will continue to show a full bar."] = true
L["Bar Texture"] = true